const { UUID, STRING, DATE, UUIDV4, TEXT } = require("sequelize");
module.exports = {
  id: { type: UUID, defaultValue: UUIDV4, primaryKey: true },
  department: STRING,
  code: STRING,
  name: STRING,
  type: STRING,
  major_type: STRING,
  minor_type: STRING,
  recruitment: STRING,
  phone: STRING,
  education: STRING,
  degree: STRING,
  gender: STRING,
  experience: STRING,
  politic: STRING,
  nation: STRING,
  age: STRING,
  household: STRING,
  major: TEXT,
  remarks: STRING,
  created_at: DATE,
  updated_at: DATE,
  province_id: STRING,
  year: STRING,
};
